# Generated by Django 5.2.6 on 2025-09-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_image/%Y/%m/%d/"
                    ),
                ),
                (
                    "small_description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("original_price", models.FloatField(default=0.0)),
                ("selling_price", models.FloatField(default=0.0)),
                ("tags", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0=default, 1=Hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0=default, 1=Trending"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "meta_keywords",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="store_produ_name_5e57da_idx"),
                    models.Index(fields=["slug"], name="store_produ_slug_361302_idx"),
                ],
            },
        ),
    ]
