# Generated by Django 5.2.6 on 2025-09-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="category_image/%Y/%m/%d/"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0=default, 1=Hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0=default, 1=Trending"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "meta_keywords",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="category_ca_name_654722_idx"),
                    models.Index(fields=["slug"], name="category_ca_slug_6890c5_idx"),
                ],
            },
        ),
    ]
